### ISSUE TITLE
Problems with BoneAppetit w/new release

### ISSUE THREAD

**Issue by Galarice** [Valheim-Modding/JotunnModStub#14]
[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Inventory and name AddItem and parameters (string, int, int, int, long, string)
[Error  : Unity Log] ArgumentException: Undefined target method for patch method static void BoneAppetit.Patch+PatchInventory::Postfix(string name, int stack, int quality, int variant, long crafterID, string crafterName)
Stack trace:
HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: Patching exception in method null
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.CreateAndPatchAll (System.Reflection.Assembly assembly, System.String harmonyInstanceId) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Boneappetit.BoneAppetit.Awake () (at <01b142689086491796cf15a3c5a94121>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.UI.Image:OnCanvasHierarchyChanged()

**Comment by MSchmoecker** [comment]
Please redirect this report to BoneAppetit https://github.com/RockerKitten/BoneAppetit/issues, as the patch is applied there.
