### ISSUE TITLE
New Proj have conflict w/ Cecil 10.5 vs 11.5 

### ISSUE THREAD

**Issue by ZenDragonX** [Valheim-Modding/JotunnModStub#19]
When starting a new project from scratch using this template it has compiler warnings on first build with a conflict on the Cecil version.  It is using 10.5 but that does not work.  Need to manually install Cecil 11.5 from nuget in order for the project to compile without warnings.

**Comment by ZenDragonX** [comment]
Hmm.. I take that back, perhaps I was running an old version.  I just updated to JVL 2.20.1 from 2.19.x (I forget the minor version) and it seems to no longer be an issue.  NOTE: however it does seem that this project template ships with v2.19.x

**Comment by MSchmoecker** [comment]
yes this was fixed in Jotunn 2.20.1, Mono.Cecil is now referenced from the game folder. The mod stub reference is now updated as well
