### ISSUE TITLE
some mods failing/unrecognized

### ISSUE THREAD

**Issue by DrTim93** [Valheim-Modding/JotunnModStub#5]
i dont know much about unity, assemblies and such so ill just post the log and maybe you could find what the problem is.
im familiar with C# .NET, java, SQL and XML 

[Player.log](https://github.com/Valheim-Modding/JotunnModStub/files/7289753/Player.log)

**Comment by sirskunkalot** [comment]
This is not a problem of Jötunn. Some mod is not working. Unfortunately I can't tell which one it is from the log.
