### ISSUE TITLE
Copy command wrong destination?

### ISSUE THREAD

**Issue by FelixReuthlinger** [Valheim-Modding/JotunnModStub#7]
https://github.com/Valheim-Modding/JotunnModStub/blob/f610ec92c7cde9f92609278e164ccb498001d2ff/publish.ps1#L74

Isn't this copy command built the wrong way around? The file doesn't exist in the "Package" folder but should be copied there, if I am not mistaken.

**Comment by sirskunkalot** [comment]
Err, I fixed this here https://github.com/Valheim-Modding/JotunnModStub/commit/0955163ffc81ef540a373cff37fd294b5bfe212a#diff-afb2069cfce34b15c0bc6e7858f9c734ed752c44849d169dff67207097e6657e. Seems like it found it's way back again. Good catch, gonna fix it rn.

**Comment by sirskunkalot** [comment]
Fixed in 3ef2a6d946195df9e6a6418af75a4bc4d45bff04
